defaults: &defaults
  encoding: unicode
  host: localhost

pg: &pg
  adapter: postgresql
  encoding: unicode
  pool: 5

login: &login
  username: 'postgres'
  password: 'root'

development:
  <<: *defaults  
  <<: *pg
  <<: *login
  database: shopify_development

test:
  <<: *pg
  <<: *login  
  database: shopify_test


production:
  <<: *pg
  <<: *login
  database: shopify_production
