default: &sqlite
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *sqlite
  database: db/development.sqlite3

test:
  <<: *sqlite
  database: db/test.sqlite3

pg: &pg
  adapter: postgresql
  encoding: unicode
  pool: 5

login: &login
  username: 'postgres'
  password: 'root'

production:
  <<: *postgres
  <<: *login
  database: shopify_production